### ISSUE TITLE
Library ?

### ISSUE THREAD

**Issue by mathieuleclaire** [lihaoyi/scala-js-fiddle#18]
Hi,
scala-js-fiddle is really a nice project concerning many aspects, congrats !

Is it in your plans to provide it as a library ? 
I need to code exactly the same behaviour in my project, and typically the server services should be very usefull if I could use it as such.

Thanks

**Comment by lihaoyi** [comment]
I'd say for now just fork it. I don't think I'll be able to put together a "reasonable" API for it to be usable as a library!
